name = "prospect-tracker"
compatibility_date = "2025-04-01"
pages_build_output_dir = "./dist/client"

[[d1_databases]]
binding = "DB"
database_name = "prospect-tracker-db"
database_id = "local-dev-db"
